name: install and test backend

on:
  push:
    branches:
      - main
      - '*.*.*'  # Match tags in the format x.y.z

  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build backend
        run: mvn -B compile --file pom.xml

      - name: Run unit and integration tests
        run: mvn -B test --file pom.xml

      - name: Update dependency graph
        uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Configure Git Identity
        run: |
            git config --global user.email "jakubmikulaa@gmail.com"
            git config --global user.name "yekxp"
      - name: Create and publish release
        run: mvn -B release:clean release:prepare release:perform --file pom.xml
