FROM eclipse-temurin:17-jdk-jammy
WORKDIR /app
COPY ../../.mvn .mvn
COPY ../../mvnw pom.xml ./
RUN sed -i 's/\r$//' mvnw
RUN ./mvnw dependency:resolve

COPY ../../src ./src

CMD ["./mvnw", "spring-boot:run"]
