name: Release packages
on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build and Deploy
      run: mvn -B deploy --file pom.xml
      env:
        CI: true
        MAVEN_CLI_OPTS: -s .github/settings.xml
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
